# Generated by Django 5.0.3 on 2024-05-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_userprofile_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="otp",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
