<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-06-30 10:19
=======
# Generated by Django 5.0.3 on 2024-06-06 05:45
>>>>>>> origin/yaser

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('account', '0004_userprofile_otp_userprofile_otp_expiry'),
=======
        ("account", "0004_userprofile_otp_userprofile_otp_expiry"),
>>>>>>> origin/yaser
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='userprofile',
            name='otp',
=======
            model_name="userprofile",
            name="otp",
>>>>>>> origin/yaser
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
