# Generated by Django 5.0.3 on 2024-06-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_userprofile_otp_userprofile_otp_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="otp",
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
