# Generated by Django 5.0.3 on 2024-06-11 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_userprofile_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^09\\d{9}$", message="شماره وارد شده معتبر نمی باشد"
                    )
                ],
            ),
        ),
    ]
