# Generated by Django 5.0.3 on 2024-06-12 11:21

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_userprofile_otp"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[
                ("objects", account.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mobile_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^09\\d{9}$", message="شماره وارد شده معتبر نمی باشد"
                    )
                ],
                verbose_name="شماره  تلفن همراه",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_status",
            field=models.CharField(
                choices=[
                    ("normal", "کاربر عادی"),
                    ("verified", "کاربر تایید شده"),
                    ("admin_level_a", "کاربر ادمین سطح a"),
                    ("admin_level_b", "کاربر ادمین سطح b"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
