# Generated by Django 5.0.3 on 2024-06-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userprofile_otp'),
        ('account', '0008_alter_userprofile_managers_and_more'),
    ]

    operations = [
    ]
