# Generated by Django 5.0.3 on 2024-07-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_userprofile_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "مرد"), ("female", "زن")],
                default="male",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
