# Generated by Django 5.0.3 on 2024-07-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userprofile_gender'),
        ('account', '0009_merge_20240630_1427'),
    ]

    operations = [
    ]
