# Generated by Django 5.0.3 on 2025-02-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referrer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
