# Generated by Django 5.0.3 on 2024-04-10 09:13

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('css', models.CharField(max_length=7)),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image_room/')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=5, max_length=9, prefix='', unique=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('canceled', 'کنسل شده'), ('expired', 'منقضی شده')], default='pending_payment', max_length=20)),
                ('bufferAfter', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_reservations', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.resource')),
            ],
        ),
    ]
