# Generated by Django 5.0.3 on 2024-04-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='capacity',
        ),
        migrations.AddField(
            model_name='resource',
            name='number_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='number_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='number_pad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
