# Generated by Django 5.0.3 on 2024-04-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_remove_reservation_user_author_reservation_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateField(),
        ),
    ]
