# Generated by Django 5.0.3 on 2024-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_alter_reservation_end_alter_reservation_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateField(),
        ),
    ]
