# Generated by Django 5.0.3 on 2024-04-07 12:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_alter_reservation_end_alter_reservation_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserve_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=5, max_length=9, prefix='', unique=True),
        ),
    ]
