# Generated by Django 5.0.3 on 2024-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_reservation_reserve_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('canceled', 'کنسل شده'), ('expired', 'منقضی شده')], default='pending_payment', max_length=20),
        ),
    ]
