# Generated by Django 5.0.3 on 2024-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_rename_bufferafter_reservation_cleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('canceled', 'کنسل شده'), ('expired', 'منقضی شده'), ('cleaning', 'نظافت')], default='pending_payment', max_length=20),
        ),
    ]
