# Generated by Django 5.0.3 on 2024-04-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='color',
            new_name='css',
        ),
    ]
