# Generated by Django 5.0.3 on 2024-04-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_rename_color_resource_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bufferAfter',
            field=models.BooleanField(default=False),
        ),
    ]
