# Generated by Django 5.0.3 on 2024-05-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_resource_capacity_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='more_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
