# Generated by Django 5.0.3 on 2024-05-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_reservation_more_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
