# Generated by Django 5.0.3 on 2024-05-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_alter_resource_price_alter_resource_price_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_pay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
