# Generated by Django 5.0.3 on 2024-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_reservation_total_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('canceled', 'کنسل شده'), ('closetime', 'زمان تعطیلی')], default='pending_payment', max_length=20),
        ),
    ]
