# Generated by Django 5.0.3 on 2024-06-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0012_reservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('onlocalpay', 'پرداخت حضوری'), ('canceled', 'کنسل شده'), ('closetime', 'زمان تعطیلی')], default='pending_payment', max_length=20),
        ),
    ]
