# Generated by Django 5.0.3 on 2024-06-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reserve", "0012_reservation_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="css",
        ),
    ]
