# Generated by Django 5.0.3 on 2024-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserve", "0013_remove_resource_css"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start",
            field=models.DateTimeField(null=True),
        ),
    ]
