# Generated by Django 5.0.3 on 2024-06-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0013_alter_reservation_status'),
        ('reserve', '0015_alter_reservation_created_at_and_more'),
    ]

    operations = [
    ]
