# Generated by Django 5.0.3 on 2024-07-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reserve", "0015_alter_reservation_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="payment_id",
        ),
    ]
