# Generated by Django 5.0.3 on 2024-07-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserve", "0016_remove_reservation_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "در انتظار پرداخت"),
                    ("confirmed", "تایید شده"),
                    ("cancelled", "کنسل شده"),
                    ("closetime", "زمان تعطیلی"),
                    ("cleaning", "زمان نظافت"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
