# Generated by Django 5.0.3 on 2024-07-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reserve", "0018_resource_css"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="css",
            new_name="cssClass",
        ),
    ]
