# Generated by Django 5.0.3 on 2024-07-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0016_merge_20240630_1427'),
        ('reserve', '0019_rename_css_resource_cssclass'),
    ]

    operations = [
    ]
