# Generated by Django 5.0.3 on 2024-07-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0020_merge_20240714_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('onlocalpay', 'پرداخت حضوری'), ('canceled', 'کنسل شده'), ('closetime', 'زمان تعطیلی'), ('cleaning', 'زمان نظافت')], default='pending_payment', max_length=20),
        ),
    ]
