# Generated by Django 5.0.3 on 2024-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0021_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='peak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
