# Generated by Django 5.0.3 on 2024-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0022_resource_peak_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
