# Generated by Django 5.0.3 on 2025-02-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_is_active'),
        ('reserve', '0026_reservation_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.coupon'),
        ),
    ]
