# Generated by Django 5.0.3 on 2025-03-17 22:43

import django.db.models.deletion
import reserve.models
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0027_alter_reservation_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_image_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=5, max_length=9, prefix='', unique=True)),
                ('images', models.ImageField(upload_to=reserve.models.get_images_upload_path_resourse)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resourse_images', to='reserve.resource')),
            ],
            options={
                'verbose_name_plural': 'Resource Images',
            },
        ),
    ]
