# Generated by Django 5.0.3 on 2025-03-17 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_coupon_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_user_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
