# Generated by Django 5.0.3 on 2024-07-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0021_alter_reservation_status'),
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_by_stuff',
        ),
        migrations.AlterField(
            model_name='payment',
            name='cost_paid',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refrence_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserve.reservation'),
        ),
    ]
