# Generated by Django 5.0.3 on 2024-07-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserve", "0016_remove_reservation_payment_id"),
        ("zarinpal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="reserve.reservation"
            ),
        ),
    ]
