# Generated by Django 5.0.3 on 2024-07-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='refrence_id',
            field=models.CharField(max_length=20),
        ),
    ]
