# Generated by Django 5.0.3 on 2024-07-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zarinpal", "0002_alter_payment_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid_by_stuff",
        ),
        migrations.AlterField(
            model_name="payment",
            name="discount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=256),
        ),
    ]
