# Generated by Django 5.0.3 on 2024-07-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zarinpal", "0003_remove_payment_paid_by_stuff_alter_payment_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="cost_paid",
            field=models.DecimalField(decimal_places=3, max_digits=65),
        ),
        migrations.AlterField(
            model_name="payment",
            name="discount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=65),
        ),
    ]
