# Generated by Django 5.0.3 on 2025-02-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0002_remove_payment_paid_by_stuff_alter_payment_cost_paid_and_more'),
        ('zarinpal', '0003_alter_payment_discount'),
    ]

    operations = [
    ]
