# Generated by Django 5.0.3 on 2024-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zarinpal", "0004_alter_payment_cost_paid_alter_payment_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="cost_paid",
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
        migrations.AlterField(
            model_name="payment",
            name="discount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="payment",
            name="refrence_id",
            field=models.CharField(max_length=100),
        ),
    ]
