# Generated by Django 5.0.3 on 2024-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zarinpal", "0005_alter_payment_cost_paid_alter_payment_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="refrence_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
